apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-info-app
spec:
  replicas: 1  # Set the desired number of replicas for your application
  selector:
    matchLabels:
      app: student-info-app
  template:
    metadata:
      labels:
        app: student-info-app
    spec:
      containers:
      - name: student-info-container
        image: your-docker-repo/student-info:latest  # Replace this with the actual image name and version
        ports:
        - containerPort: 8081
